### ISSUE TITLE
'jupyter' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

### ISSUE THREAD

**Issue by denfromufa** [jupyter/atom-notebook#31]
events.js:141 Uncaught Error: spawn jupyter ENOENT

No running Jupyter session. Try closing and re-opening this file.

**Comment by gnestor** [comment]
Try setting the path of your jupyter binary in Atom > Settings > Packages > jupyter-notebook > Settings > Path to jupyter binary. If you don't know your jupyter path, try `which jupyter` in your terminal. My jupyter path on OS X is /usr/local/bin/. Once jupyter-notebook can find your jupyter binary, you should be able to open notebooks.

**Comment by denfromufa** [comment]
This did not work, I'm on windows. Python 2.7

**Comment by gnestor** [comment]
Have you confirmed the jupyter path that you added in terminal?

> On Jan 20 2016, at 8:43 am, denfromufa &lt;notifications@github.com&gt;
wrote:  
This did not work, I'm on windows. Python 2.7  
  
On Wed, Jan 20, 2016, 10:25 AM Grant Nestor &lt;notifications@github.com&gt;  
wrote:  
  
&gt; Try setting the path of your jupyter binary in Atom &gt; Settings &gt;
Packages  
&gt; &gt; jupyter-notebook &gt; Settings &gt; Path to jupyter binary. If you
don't know  
&gt; your jupyter path, try which jupyter in your terminal. My jupyter path on  
&gt; OS X is /usr/local/bin/. Once jupyter-notebook can find your jupyter  
&gt; binary, you should be able to open notebooks.  
&gt;  
&gt; —  
&gt; Reply to this email directly or view it on GitHub  
&gt; &lt;https://github.com/jupyter/atom-
notebook/issues/31#issuecomment-173260309&gt;  
&gt; .  
&gt;  

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/jupyter
/atom-notebook/issues/31#issuecomment-173267142).![](https://github.com/notifi
cations/beacon/AAfRYmY2pd1EJvO_OMDSv2hxXS4UWS63ks5pb7CZgaJpZM4HItuf.gif)

**Comment by denfromufa** [comment]
Yes, I set the path to Jupyter full path, BTW on Windows the command is
"where jupyter"

**Comment by gnestor** [comment]
Related https://github.com/jupyter/atom-notebook/issues/29

**Comment by gnestor** [comment]
1. Add your jupyter path to your Atom path in your init script (Command Palette > Init Script): process.env.PATH = process.env.PATH + ';YOUR_PATH'
2. Reload Atom (Command Palette > Reload)
3. Try opening a notebook
4. If that doesn't work, try opening Atom from your project directory from the terminal: `atom .`
5. If that doesn't work, check the console in Atom's Developer Tools and share the full stack trace.

**Comment by auneri** [comment]
I've pinpointed the error to a missing kernelgateway.exe, as reported in the developer console:

> kernelGateway.stderr jupyter: 'kernelgateway' is not a Jupyter command

This is due to the [following issue](https://github.com/jupyter-incubator/kernel_gateway/issues/78), which has been fixed *very* recently. Installing from the master branch via
```
pip install --user git+https://github.com/jupyter-incubator/kernel_gateway.git@master
```
did the trick for me. Hopefully the changes will be distributed in a proper release soon.

**Comment by gnestor** [comment]
Good to hear 👍

**Comment by denfromufa** [comment]
I do not understand why this issue was closed without my verification. I installed kernel_gateway from master and still get the same error and traceback:

```
index.js:52 Window load time: 2834ms
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
/C:/Users/denis/.atom/packages/jupyter-notebook/lib/notebook-editor.js:222 NotebookEditor created for C:\MSi_Projects\Pluto\Utilities\coolprop_ethylene_glycol.ipynb
C:\Users\denis\AppData\Local\atom\app-1.4.0\resources\app.asar\src\scrollbar-component.js:86 ::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
events.js:141 Uncaught Error: spawn jupyter ENOENT
4/C:/Users/denis/.atom/packages/jupyter-notebook/lib/notebook-editor.js:77 Action 'Symbol(cell_source_changed)'received in NotebookEditor
```

**Comment by gnestor** [comment]
@denfromufa Are you still running into this issue?

**Comment by denfromufa** [comment]
I can check with latest if you have any changes or suggestions.

**Comment by gnestor** [comment]
1. Try updating Kernel Gateway: `pip install --user git+https://github.com/jupyter-incubator/kernel_gateway.git@master` or `pip3 install git+https://github.com/jupyter-incubator/kernel_gateway.git@master`
2. Make sure jupyter-notebook is updated 
3. Verify that the path of your jupyter binary is one of the [defaults](https://github.com/jupyter/atom-notebook/blob/master/lib/main.js#L68) or added to the jupyter-notebook settings
3. Try opening a notebook

**Comment by denfromufa** [comment]
what if jupyter is in system path?

**Comment by denfromufa** [comment]
tried uninstalling jupyter notebook from atom:

```
Uninstalling “jupyter-notebook” failed.Hide output…
Failed to delete jupyter-notebook: ENOTEMPTY, directory not empty 'C:\Users\denis.akhiyarov\.atom\packages\jupyter-notebook\node_modules\react\node_modules\envify\node_modules\jstransform\src'
```

**Comment by gnestor** [comment]
Try `rm -r C:\Users\denis.akhiyarov\.atom\packages\jupyter-notebook` and then re-install (not sure if that command works on Windows...)

**Comment by denfromufa** [comment]
del instead of -rm -r. now it is broken.

**Comment by gnestor** [comment]
Don't know what you mean by that. Can you reinstall? Have you tried `apm install jupyter-notebook`? `PYTHON=python2 apm install`?

**Comment by denfromufa** [comment]
Why do I need second command?

**Comment by denfromufa** [comment]
I meant that Jupyter notebook package cannot be uninstalled from atom gui

**Comment by gnestor** [comment]
If the `apm install jupyter-notebook` fails, you can try `PYTHON=python2 apm install`.

**Comment by denfromufa** [comment]
first one failed, what is the second one doing?

**Comment by rgbkrk** [comment]
The `PYTHON=python2` is explicitly setting which Python to use for node-gyp which sadly requires Python 2.

**Comment by denfromufa** [comment]
PYTHON: can't open file '=python2': [Errno 2] No such file or directory

**Comment by rgbkrk** [comment]
Hmmmm. Maybe on Windows you have to do:

```
SET PYTHON=python2
apm install jupyter-notebook
```

**Comment by denfromufa** [comment]
```
 "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp
npm ERR! This is most likely a problem with the runas packag
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.
```

**Comment by denfromufa** [comment]
```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.ta
rgets(57,5): error MSB8020: The build tools for v120 (Platform Toolset = 'v120')
 cannot be found. To build using the v120 build tools, please install v120 build
 tools.  Alternatively, you may upgrade to the current Visual Studio tools by se
lecting the Project menu or right-click the solution, and then selecting "Retarg
et solution". [C:\Users\denis.akhiyarov\AppData\Local\Temp\apm-install-dir-11613
-19844-8heuj8\node_modules\jupyter-notebook\node_modules\ws\node_modules\bufferu
til\build\bufferutil.vcxproj]
```

**Comment by megamindbrian** [comment]
I set the path and I still get this error: /Users/<username>/miniconda3/envs/py36/bin/jupyter
