### ISSUE TITLE
ViewRegistry.addViewProvider is deprecated.

### ISSUE THREAD

**Issue by shafreeck** [jupyter/atom-notebook#48]
atom.views.addViewProvider now takes 2 arguments: a model constructor and a createView function. See docs for details.
```
ViewRegistry.addViewProvider (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:52:18)
Object.activate (/Users/shafreeck/.atom/packages/jupyter-notebook/lib/main.js:51:16)
Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32)
Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26)
```

**Comment by srinathv** [comment]
atom.views.addViewProvider now takes 2 arguments: a model constructor and a createView function. See docs for details.
Report Issue
ViewRegistry.addViewProvider - /Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:50:18
Object.activate - /Users/srinathv/.atom/packages/jupyter-notebook/lib/main.js:51:16
Package.activateNow - /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:191:19
<unknown> - /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:164:32
Package.measure - /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:94:15
<unknown> - /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:157:26

**Comment by gnestor** [comment]
This repo is not being actively maintained 🙁 In the meantime, I suggest that you look at [hydrogen](https://github.com/nteract/hydrogen) to run code inline in Atom's text editor, [nteract](https://github.com/nteract/nteract) (a new Jupyter notebook client built using Electron, React, Redux, RxJS), [Jupyter Notebook](https://github.com/jupyter/notebook), and [JupyterLab](https://github.com/jupyterlab/jupyterlab). 

Having said that, nteract is currently extracting its many components into separate packages which will allow them to be reused and assembled to create new apps. When I have the time, I would like to use them to completely refactor this project.

**Comment by JHonaker** [comment]
This is fixed by pull request #66

**Comment by BenjaminHCCarr** [comment]
Can we get this pushed to the apm network?
I am on `jupyter-notebook` `v0.0.9` with no updates available through atom or apm and still getting this error.

**Comment by gnestor** [comment]
@JHonaker Thanks!

**Comment by gnestor** [comment]
@BenjaminHCCarr It's currently listed on apm: https://atom.io/packages/jupyter-notebook

However, this project is not being actively maintained, but we're looking for help!

**Comment by BenjaminHCCarr** [comment]
I meant the jupyter/atom-notebook#66 fix.

I know it's not active, but to make it work in the atom repo would be great.
